// <auto-generated />
using System;
using EzgiBlog.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EzgiBlog.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231213195449_SeedCompleted")]
    partial class SeedCompleted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EzgiBlog.Entity.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee619251-f8b5-4f47-970c-182a332d3b41"),
                            CategoryId = new Guid("73cdf461-2e7b-42d8-9fc3-ae5525a5116b"),
                            Content = "Lorem ipsum dolor sit amet consectetur adipiscing elit mattis cras, sed etiam sodales mus pretium dapibus magna varius ut, tellus euismod eget dis porta magnis lacinia ac. Nascetur iaculis interdum facilisi donec nunc hendrerit sem integer vestibulum, ad proin ultrices magna cum consequat lacinia tempus, duis phasellus venenatis pulvinar mauris vehicula suscipit a. Neque rutrum erat arcu volutpat tortor fames leo vestibulum iaculis curae porta sociosqu, sagittis tincidunt lectus mi nec morbi parturient mus metus dictumst aptent vel, sodales accumsan penatibus cras porttitor nisl montes ullamcorper ornare non urna.\r\n\r\nLacus venenatis at morbi feugiat purus accumsan lectus enim pulvinar quis augue sociosqu, porta luctus montes metus felis mauris aliquam arcu leo vivamus facilisis, sed viverra suspendisse sapien blandit commodo scelerisque molestie libero cras ultrices. Quis feugiat semper gravida aliquam sapien blandit at penatibus nec nibh aenean porttitor, fusce justo dapibus lacinia vitae convallis et venenatis faucibus laoreet per. Vestibulum senectus at et bibendum fames risus molestie facilisi, libero quisque lacinia nunc platea donec mattis, aliquet ligula tristique conubia mauris primis metus.",
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 12, 13, 22, 54, 48, 930, DateTimeKind.Local).AddTicks(6872),
                            ImageId = new Guid("9849715d-6968-4a5e-b468-638e8f4b556e"),
                            IsDeleted = false,
                            Title = "Asp.Net Deneme Makalesi 1",
                            ViewCount = 15
                        },
                        new
                        {
                            Id = new Guid("0efcb438-64c6-40b5-89dd-2eaa5c9e6eea"),
                            CategoryId = new Guid("67966216-8006-46e1-aba2-befbfcc8be13"),
                            Content = "Visual Studio dolor sit amet consectetur adipiscing elit mattis cras, sed etiam sodales mus pretium dapibus magna varius ut, tellus euismod eget dis porta magnis lacinia ac. Nascetur iaculis interdum facilisi donec nunc hendrerit sem integer vestibulum, ad proin ultrices magna cum consequat lacinia tempus, duis phasellus venenatis pulvinar mauris vehicula suscipit a. Neque rutrum erat arcu volutpat tortor fames leo vestibulum iaculis curae porta sociosqu, sagittis tincidunt lectus mi nec morbi parturient mus metus dictumst aptent vel, sodales accumsan penatibus cras porttitor nisl montes ullamcorper ornare non urna.\r\n\r\nLacus venenatis at morbi feugiat purus accumsan lectus enim pulvinar quis augue sociosqu, porta luctus montes metus felis mauris aliquam arcu leo vivamus facilisis, sed viverra suspendisse sapien blandit commodo scelerisque molestie libero cras ultrices. Quis feugiat semper gravida aliquam sapien blandit at penatibus nec nibh aenean porttitor, fusce justo dapibus lacinia vitae convallis et venenatis faucibus laoreet per. Vestibulum senectus at et bibendum fames risus molestie facilisi, libero quisque lacinia nunc platea donec mattis, aliquet ligula tristique conubia mauris primis metus.",
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 12, 13, 22, 54, 48, 930, DateTimeKind.Local).AddTicks(6878),
                            ImageId = new Guid("8d9a4895-7412-4162-ac2a-732fdcc4d28f"),
                            IsDeleted = false,
                            Title = "Visual Studio Deneme Makalesi 1",
                            ViewCount = 15
                        });
                });

            modelBuilder.Entity("EzgiBlog.Entity.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73cdf461-2e7b-42d8-9fc3-ae5525a5116b"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 12, 13, 22, 54, 48, 930, DateTimeKind.Local).AddTicks(7047),
                            IsDeleted = false,
                            Name = "ASP NET Core"
                        },
                        new
                        {
                            Id = new Guid("67966216-8006-46e1-aba2-befbfcc8be13"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 12, 13, 22, 54, 48, 930, DateTimeKind.Local).AddTicks(7052),
                            IsDeleted = false,
                            Name = "ASP NET Core"
                        });
                });

            modelBuilder.Entity("EzgiBlog.Entity.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9849715d-6968-4a5e-b468-638e8f4b556e"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 12, 13, 22, 54, 48, 930, DateTimeKind.Local).AddTicks(7178),
                            FileName = "images/testimage",
                            FileType = "jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("8d9a4895-7412-4162-ac2a-732fdcc4d28f"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 12, 13, 22, 54, 48, 930, DateTimeKind.Local).AddTicks(7181),
                            FileName = "images/vstest",
                            FileType = "png",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("EzgiBlog.Entity.Entities.Article", b =>
                {
                    b.HasOne("EzgiBlog.Entity.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EzgiBlog.Entity.Entities.Image", "Image")
                        .WithMany("Articles")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("EzgiBlog.Entity.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("EzgiBlog.Entity.Entities.Image", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
